import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000');
 await page.getByRole('button',{name:'iPhone dưới 15 triệu',exact:true}).click();
 await page.waitForFunction(()=>['Updated','Request failed'].includes(document.querySelector('#status').textContent),{},{timeout:180000});
 assert.equal(await page.locator('#status').textContent(),'Updated');
 const initialState=JSON.parse(await page.locator('#state').textContent());
 assert.equal(initialState.dataModel.dataSource.kind,'chotot-live');
 assert.ok(initialState.dataModel.ads.length>0);
 assert.equal(await page.locator('.ad-card').count(),initialState.dataModel.ads.length);
 assert.ok(initialState.dataModel.ads.every(a=>a.list_id>1000000&&a.source==='chotot-live'));
 assert.match(await page.locator('#trace').textContent(),/gateway.chotot.com/);
 await page.getByRole('button',{name:'Cá nhân',exact:true}).click();
 await page.waitForFunction(()=>['Updated','Request failed'].includes(document.querySelector('#status').textContent),{},{timeout:180000});
 assert.equal(await page.locator('#status').textContent(),'Updated');
 const filtered=JSON.parse(await page.locator('#state').textContent());
 assert.ok(filtered.dataModel.ads.length>0);
 assert.ok(filtered.dataModel.ads.every(a=>a.account_type==='p'));
 const selectedId=filtered.dataModel.ads[0].list_id;
 await page.getByRole('button',{name:'Xem chi tiết',exact:true}).first().click();
 await page.waitForFunction(()=>['Updated','Request failed'].includes(document.querySelector('#status').textContent),{},{timeout:180000});
 assert.equal(await page.locator('#status').textContent(),'Updated');
 const detail=JSON.parse(await page.locator('#state').textContent());
 assert.equal(detail.dataModel.ads[0].list_id,selectedId);
 assert.match(detail.dataModel.dataSource.url,/v2\/public\/ad-listing/);
 assert.equal(await page.locator('.ad-card').count(),1);
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Real Chợ Tốt + Codex search → filter → detail passed; mobile overflow and browser errors passed.');
}finally{await browser.close();}
